require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

if "#{ENV['KLIPPA_SCANNER_SDK_USERNAME']}" == ""
  ENV['KLIPPA_SCANNER_SDK_USERNAME'] = '{your-username}'
end

if "#{ENV['KLIPPA_SCANNER_SDK_PASSWORD']}" == ""
  ENV['KLIPPA_SCANNER_SDK_PASSWORD'] = '{your-password}'
end

target 'KlippaScannerSdkExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  if "#{ENV['KLIPPA_SCANNER_SDK_URL']}" == ""
    file_path = File.expand_path('../../ios/.sdk_repo', __dir__)
    ENV['KLIPPA_SCANNER_SDK_URL'] = File.read(file_path).strip
  end

  if "#{ENV['KLIPPA_SCANNER_SDK_VERSION']}" == ""
    file_path = File.expand_path('../../ios/.sdk_version', __dir__)
    ENV['KLIPPA_SCANNER_SDK_VERSION'] = File.read(file_path).strip
  end

  pod 'Klippa-Scanner', podspec: "#{ENV['KLIPPA_SCANNER_SDK_URL']}/#{ENV['KLIPPA_SCANNER_SDK_USERNAME']}/#{ENV['KLIPPA_SCANNER_SDK_PASSWORD']}/KlippaScanner/#{ENV['KLIPPA_SCANNER_SDK_VERSION']}.podspec"

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
